apiVersion: metal.ironcore.dev/v1alpha1
kind: Server
metadata:
  labels:
    topology.metal.ironcore.dev/rack: "2"
    topology.metal.ironcore.dev/heightunit: "4"
  name: server-2-4
spec:
  systemUUID: "00000000-0000-0000-0000-000000000204"
  bmcRef:
    name: sample-bmc
  power: "Off"
  indicatorLED: "Off"
