version = 1
SPDX-PackageName = "metal-operator"
SPDX-PackageSupplier = "IronCore authors <ospo@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/ironcore-dev/metal-operator"

[[annotations]]
path = [
    ".devcontainer/**",
    ".github/**",
    ".gitignore",
    ".dockerignore",
    ".golangci.yml",
    ".custom-gcl.yml",
    "CODEOWNERS",
    "Dockerfile",
    "Makefile",
    "PROJECT",
    "config/**",
    "dist/**",
    "go.mod",
    "go.sum",
    "mkdocs.yml",
    "REUSE.toml",
    "hack/**",
    "package.json",
    "package-lock.json",
    "internal/cmd/visualizer/index.html",
    "test/data/*.json",
    "test/data/*.yaml"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP SE or an SAP affiliate company and IronCore contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "docs/**",
    "README.md",
    "AGENTS.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP SE or an SAP affiliate company and IronCore contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "bmc/mock/server/data/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2016-2024, Contributing Member(s) of Distributed Management Task Force, Inc.. All rights reserved."
SPDX-License-Identifier = "BSD-3-Clause"
