apiVersion: metal.ironcore.dev/v1alpha1
kind: Server
metadata:
  labels:
    topology.metal.ironcore.dev/rack: "1"
    topology.metal.ironcore.dev/heightunit: "3"
  name: server-1-3
spec:
  systemUUID: "00000000-0000-0000-0000-000000000103"
  bmcRef:
    name: sample-bmc
  power: "Off"
  indicatorLED: "Off"
