apiVersion: metal.ironcore.dev/v1alpha1
kind: Server
metadata:
  labels:
    topology.metal.ironcore.dev/rack: "1"
    topology.metal.ironcore.dev/heightunit: "4"
  name: server-1-4
spec:
  bmcRef:
    name: sample-bmc
  power: "Off"
  indicatorLED: "Off"
