apiVersion: metal.ironcore.dev/v1alpha1
kind: Server
metadata:
  labels:
    topology.metal.ironcore.dev/rack: "1"
    topology.metal.ironcore.dev/heightunit: "2"
  name: server-1-2
spec:
  systemUUID: "00000000-0000-0000-0000-000000000102"
  bmcRef:
    name: sample-bmc
  power: "Off"
  indicatorLED: "On"
