apiVersion: metal.ironcore.dev/v1alpha1
kind: Server
metadata:
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: server-sample
    app.kubernetes.io/part-of: metal-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: metal-operator
  name: endpoint-sample-system-0
spec:
  systemUUID: "00000000-0000-0000-0000-000000000001"
  bmcRef:
    name: bmc-sample
  power: "Off"
  indicatorLED: Blinking
