apiVersion: metal.ironcore.dev/v1alpha1
kind: BMCSecret
metadata:
  labels:
    app.kubernetes.io/name: bmcsecret
    app.kubernetes.io/instance: bmcsecret-sample
    app.kubernetes.io/part-of: metal-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: metal-operator
  name: bmcsecret-sample
spec:
  # TODO(user): Add fields here
