apiVersion: metal.ironcore.dev/v1alpha1
kind: Server
metadata:
  labels:
    topology.metal.ironcore.dev/rack: "3"
    topology.metal.ironcore.dev/heightunit: "8"
  name: server-3-8
spec:
  bmcRef:
    name: sample-bmc
  power: "Off"
  indicatorLED: "Off"
