apiVersion: metal.ironcore.dev/v1alpha1
kind: Server
metadata:
  labels:
    topology.metal.ironcore.dev/rack: "3"
    topology.metal.ironcore.dev/heightunit: "1"
  name: server-3-1
spec:
  systemUUID: "00000000-0000-0000-0000-000000000301"
  bmcRef:
    name: sample-bmc
  power: "Off"
  indicatorLED: "Off"
