apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        args:
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=127.0.0.1:8080
          - --leader-elect
          - --mac-prefixes-file=/etc/macdb/macdb.yaml
          - --probe-image=ghcr.io/ironcore-dev/metalprobe:latest
          - --probe-os-image=ghcr.io/ironcore-dev/os-images/gardenlinux:1443.10
          - --registry-url=http://127.0.0.1:30000
          - --registry-port=30000
          - --enforce-first-boot
          - --fmi-server-address=metal-operator-fmi-server-svc:80
        ports:
        - containerPort: 30000
        volumeMounts:
        - mountPath: /etc/macdb/
          name: macdb
      - name: redfish
        image: dmtf/redfish-mockup-server:latest
        ports:
        - containerPort: 8000
      securityContext:
        runAsNonRoot: false
      volumes:
      - name: macdb
        secret:
          defaultMode: 420
          secretName: macdb
