---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.20.1
  name: bmcusers.metal.ironcore.dev
spec:
  group: metal.ironcore.dev
  names:
    kind: BMCUser
    listKind: BMCUserList
    plural: bmcusers
    singular: bmcuser
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: BMCUser is the Schema for the bmcusers API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: BMCUserSpec defines the desired state of BMCUser.
            properties:
              bmcRef:
                description: BMCRef references the BMC this user should be created
                  on.
                properties:
                  name:
                    default: ""
                    description: |-
                      Name of the referent.
                      This field is effectively required, but due to backwards compatibility is
                      allowed to be empty. Instances of this type with an empty value here are
                      almost certainly wrong.
                      More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    type: string
                type: object
                x-kubernetes-map-type: atomic
              bmcSecretRef:
                description: |-
                  BMCSecretRef references the BMCSecret containing the credentials for this user.
                  If not set, the operator will generate a secure password based on BMC manufacturer requirements.
                properties:
                  name:
                    default: ""
                    description: |-
                      Name of the referent.
                      This field is effectively required, but due to backwards compatibility is
                      allowed to be empty. Instances of this type with an empty value here are
                      almost certainly wrong.
                      More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    type: string
                type: object
                x-kubernetes-map-type: atomic
              description:
                description: Description is an optional description for the BMC user.
                type: string
              roleID:
                description: |-
                  RoleID is the ID of the role to assign to the user.
                  The available roles depend on the BMC implementation.
                  For Redfish, common role IDs are "Administrator", "Operator", "ReadOnly".
                type: string
              rotationPeriod:
                description: |-
                  RotationPeriod defines how often the password should be rotated.
                  if not set, the password will not be rotated.
                type: string
              userName:
                description: Username of the BMC user.
                type: string
            required:
            - roleID
            - userName
            type: object
          status:
            description: BMCUserStatus defines the observed state of BMCUser.
            properties:
              effectiveBMCSecretRef:
                description: |-
                  EffectiveBMCSecretRef references the BMCSecret currently used for this user.
                  This may differ from Spec.BMCSecretRef if the operator generated a password.
                properties:
                  name:
                    default: ""
                    description: |-
                      Name of the referent.
                      This field is effectively required, but due to backwards compatibility is
                      allowed to be empty. Instances of this type with an empty value here are
                      almost certainly wrong.
                      More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    type: string
                type: object
                x-kubernetes-map-type: atomic
              id:
                description: ID of the user in the BMC system
                type: string
              lastRotation:
                description: LastRotation is the timestamp of the last password rotation.
                format: date-time
                type: string
              passwordExpiration:
                description: PasswordExpiration is the timestamp when the password
                  will expire.
                format: date-time
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
