---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.20.1
  name: bmcversionsets.metal.ironcore.dev
spec:
  group: metal.ironcore.dev
  names:
    kind: BMCVersionSet
    listKind: BMCVersionSetList
    plural: bmcversionsets
    singular: bmcversionset
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.bmcVersionTemplate.version
      name: BMCVersion
      type: string
    - jsonPath: .status.fullyLabeledBMCs
      name: selectedBMCs
      type: integer
    - jsonPath: .status.availableBMCVersion
      name: AvailableBMCVersion
      type: integer
    - jsonPath: .status.pendingBMCVersion
      name: Pending
      type: integer
    - jsonPath: .status.inProgressBMCVersion
      name: InProgress
      type: integer
    - jsonPath: .status.completedBMCVersion
      name: Completed
      type: integer
    - jsonPath: .status.failedBMCVersion
      name: Failed
      type: integer
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: BMCVersionSet is the Schema for the bmcversionsets API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: BMCVersionSetSpec defines the desired state of BMCVersionSet.
            properties:
              bmcSelector:
                description: BMCSelector specifies a label selector to identify the
                  BMC that are to be selected.
                properties:
                  matchExpressions:
                    description: matchExpressions is a list of label selector requirements.
                      The requirements are ANDed.
                    items:
                      description: |-
                        A label selector requirement is a selector that contains values, a key, and an operator that
                        relates the key and values.
                      properties:
                        key:
                          description: key is the label key that the selector applies
                            to.
                          type: string
                        operator:
                          description: |-
                            operator represents a key's relationship to a set of values.
                            Valid operators are In, NotIn, Exists and DoesNotExist.
                          type: string
                        values:
                          description: |-
                            values is an array of string values. If the operator is In or NotIn,
                            the values array must be non-empty. If the operator is Exists or DoesNotExist,
                            the values array must be empty. This array is replaced during a strategic
                            merge patch.
                          items:
                            type: string
                          type: array
                          x-kubernetes-list-type: atomic
                      required:
                      - key
                      - operator
                      type: object
                    type: array
                    x-kubernetes-list-type: atomic
                  matchLabels:
                    additionalProperties:
                      type: string
                    description: |-
                      matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
                      map is equivalent to an element of matchExpressions, whose key field is "key", the
                      operator is "In", and the values array contains only "value". The requirements are ANDed.
                    type: object
                type: object
                x-kubernetes-map-type: atomic
              bmcVersionTemplate:
                description: BMCVersionTemplate defines the template for the BMCversion
                  Resource to be applied to the servers.
                properties:
                  image:
                    description: details regarding the image to use to upgrade to
                      given BMC version
                    properties:
                      URI:
                        description: The URI of the software image to update/install."
                        type: string
                      secretRef:
                        description: |-
                          ImageSecretRef is a reference to the Kubernetes Secret (of type SecretTypeBasicAuth) object that contains the credentials
                          to access the ImageURI. This secret includes sensitive information such as usernames and passwords.
                        properties:
                          name:
                            description: name is unique within a namespace to reference
                              a secret resource.
                            type: string
                          namespace:
                            description: namespace defines the space within which
                              the secret name must be unique.
                            type: string
                        type: object
                        x-kubernetes-map-type: atomic
                      transferProtocol:
                        description: The network protocol that the server's update
                          service uses to retrieve 'ImageURI'
                        type: string
                    required:
                    - URI
                    type: object
                  serverMaintenancePolicy:
                    description: ServerMaintenancePolicy is a maintenance policy to
                      be enforced on the server managed by referred BMC.
                    type: string
                  updatePolicy:
                    description: UpdatePolicy is an indication of whether the server's
                      upgrade service should bypass vendor update policies
                    type: string
                  version:
                    description: Version contains a BMC version to upgrade to
                    type: string
                required:
                - image
                - version
                type: object
            required:
            - bmcSelector
            type: object
          status:
            description: BMCVersionSetStatus defines the observed state of BMCVersionSet.
            properties:
              availableBMCVersion:
                description: AvailableBMCVersion is the number of BMCVersion current
                  created by the set.
                format: int32
                type: integer
              completedBMCVersion:
                description: CompletedBMCVersion is the total number of completed
                  BMCVersion in the set.
                format: int32
                type: integer
              failedBMCVersion:
                description: FailedBMCVersion is the total number of failed BMCVersion
                  in the set.
                format: int32
                type: integer
              fullyLabeledBMCs:
                description: FullyLabeledBMCs is the number of server in the set.
                format: int32
                type: integer
              inProgressBMCVersion:
                description: InProgressBMCVersion is the total number of BMCVersion
                  in the set that are currently in InProgress.
                format: int32
                type: integer
              pendingBMCVersion:
                description: PendingBMCVersion is the total number of pending BMCVersion
                  in the set.
                format: int32
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
