---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: bmcusers.metal.ironcore.dev
spec:
  group: metal.ironcore.dev
  names:
    kind: BMCUser
    listKind: BMCUserList
    plural: bmcusers
    singular: bmcuser
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: BMCUser is the Schema for the bmcusers API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: BMCUserSpec defines the desired state of BMCUser.
            properties:
              bmcControllerUser:
                default: false
                description: set if the user should be used by the BMC controller
                  to access the system.
                type: boolean
              bmcRef:
                description: |-
                  LocalObjectReference contains enough information to let you locate the
                  referenced object inside the same namespace.
                properties:
                  name:
                    default: ""
                    description: |-
                      Name of the referent.
                      This field is effectively required, but due to backwards compatibility is
                      allowed to be empty. Instances of this type with an empty value here are
                      almost certainly wrong.
                      More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    type: string
                type: object
                x-kubernetes-map-type: atomic
              bmcSecretRef:
                description: if not set, the operator will generate a secure password
                  based on BMC manufacturer requirements.
                properties:
                  name:
                    default: ""
                    description: |-
                      Name of the referent.
                      This field is effectively required, but due to backwards compatibility is
                      allowed to be empty. Instances of this type with an empty value here are
                      almost certainly wrong.
                      More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    type: string
                type: object
                x-kubernetes-map-type: atomic
              description:
                type: string
              enabled:
                type: boolean
              roleID:
                type: string
              rotationPeriod:
                type: string
              userName:
                type: string
            required:
            - bmcControllerUser
            - enabled
            - roleID
            - userName
            type: object
          status:
            description: BMCUserStatus defines the observed state of BMCUser.
            properties:
              effectiveBMCSecretRef:
                description: |-
                  LocalObjectReference contains enough information to let you locate the
                  referenced object inside the same namespace.
                properties:
                  name:
                    default: ""
                    description: |-
                      Name of the referent.
                      This field is effectively required, but due to backwards compatibility is
                      allowed to be empty. Instances of this type with an empty value here are
                      almost certainly wrong.
                      More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    type: string
                type: object
                x-kubernetes-map-type: atomic
              id:
                type: string
              lastRotation:
                format: date-time
                type: string
              passwordExpiration:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
